name: Build

on:
  pull_request:
    paths-ignore:
      - '.assets/**'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: api/package.json

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: api/package.json
          cache: pnpm
          cache-dependency-path: api/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm test:lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
