name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Build the application
        run: |
          cd api
          npm ci
          npm run build

      - name: rsync deployment to staging
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: api/dist/
          remote_path: /home/${{ secrets.USER_STAGING }}/www/${{ secrets.DOMAIN_STAGING }}/
          remote_host: ${{ secrets.DOMAIN_STAGING }}
          remote_port: 229
          remote_user: ${{ secrets.USER_STAGING }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}

      - name: Deploy the application to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOMAIN_STAGING }}
          username: ${{ secrets.USER_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          port: 229
          script: |
            cd www/${{ secrets.DOMAIN_STAGING }}/
            npm ci
            secrets pull -e staging